# Generated by Django 4.0.4 on 2022-05-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Cover'),
        ),
    ]
