# Generated by Django 4.0.4 on 2022-05-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cover',
        ),
    ]
