# Generated by Django 4.0.4 on 2022-05-11 11:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_comment_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=tinymce.models.HTMLField(null=True, verbose_name='Description'),
        ),
    ]
