# Generated by Django 4.0.4 on 2022-05-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_photo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
    ]
